//A function for handle ajax request generated by FormAjax::postLink() 
function postLinkAjax(formName)
{
    $.ajax({
        method: 'POST',
        url: $('form[name='+ formName +']').attr('action'),
        data: $('form[name='+ formName +']').serialize(),
        dataType: 'html',
        cache: false,
        beforeSend: function() {
            $('#ajax-indicator').fadeIn();
        }
    }).done(function(data) {
        $('#defaultGridBlock').html(data);
        
        $(".date-picker").datepicker({
            rtl:App.isRTL(),
            orientation:"auto right",
            autoclose:!0,
            clearBtn:!0
        });
    }).always(function() {
        $('#ajax-indicator').fadeOut();
    });
    
    return false;
}

//A function to handle ajax based paging and sorting requests
$(document).on('click', '.sortable-control a, ul.pagination li a', function(){
    $.ajax({
        url: $(this).attr('href'),
        dataType: 'html',
        cache: false,
        beforeSend: function() {
            $('#ajax-indicator').fadeIn();
        }
    }).done(function(data) {
        $('#defaultGridBlock').html(data);
        
        $(".date-picker").datepicker({
            rtl:App.isRTL(),
            orientation:"auto right",
            autoclose:!0,
            clearBtn:!0
        });
    }).always(function() {
        $('#ajax-indicator').fadeOut();
    });
    
    return false;
});

//A function to handle search form submission requests
$(document).on('submit', '#defaultGridBlockForm', function(){
    $.ajax({
        method: 'POST',
        url: $('#page-url').val(),
        data: $('#defaultGridBlockForm').serialize(),
        dataType: 'html',
        cache: false,
        beforeSend: function() {
            $('#ajax-indicator').fadeIn();
        }
    }).done(function(data) {
        $('#defaultGridBlock').html(data);
        
        $(".date-picker").datepicker({
            rtl:App.isRTL(),
            orientation:"auto right",
            autoclose:!0,
            clearBtn:!0
        });
    }).always(function() {
        $('#ajax-indicator').fadeOut();
    });
    
    return false;
});
